"""Generate downloadable PDF reports from structured analysis."""

import re
from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

from pipeline.schemas import ExamNotesReport


def _safe(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _markdown_to_flowables(markdown: str, heading_style, body_style, subheading_style) -> list:
    """Convert basic markdown lines to ReportLab flowables."""
    flow: list = []
    for line in markdown.splitlines():
        stripped = line.strip()
        if not stripped:
            flow.append(Spacer(1, 6))
            continue
        if stripped.startswith("### "):
            flow.append(Paragraph(_safe(stripped[4:]), subheading_style))
        elif stripped.startswith("## "):
            flow.append(Paragraph(_safe(stripped[3:]), heading_style))
        elif stripped.startswith("# "):
            flow.append(Paragraph(_safe(stripped[2:]), heading_style))
        elif stripped.startswith(("- ", "* ")):
            flow.append(Paragraph(f"• {_safe(stripped[2:])}", body_style))
        elif re.match(r"^\d+\.\s", stripped):
            flow.append(Paragraph(_safe(stripped), body_style))
        else:
            flow.append(Paragraph(_safe(stripped), body_style))
    return flow


def generate_pdf_report(analysis: ExamNotesReport, output_path: Path) -> Path:
    """Render exam notes PDF report and return its path."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Heading1"],
        fontSize=16,
        textColor=colors.HexColor("#1a365d"),
        spaceAfter=10,
        alignment=TA_CENTER,
    )
    heading_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=12,
        textColor=colors.HexColor("#2b6cb0"),
        spaceBefore=12,
        spaceAfter=6,
    )
    subheading_style = ParagraphStyle(
        "SubHeading",
        parent=styles["Heading3"],
        fontSize=11,
        textColor=colors.HexColor("#2c5282"),
        spaceBefore=8,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=9.5,
        leading=14,
        spaceAfter=6,
    )
    meta_style = ParagraphStyle(
        "Meta",
        parent=styles["Normal"],
        fontSize=8.5,
        textColor=colors.grey,
        alignment=TA_CENTER,
        spaceAfter=12,
    )
    callout_style = ParagraphStyle(
        "Callout",
        parent=body_style,
        backColor=colors.HexColor("#ebf8ff"),
        borderPadding=6,
        spaceAfter=8,
    )

    meta_parts = [analysis.exam_focus, datetime.now().strftime("%d %b %Y")]
    if analysis.theme:
        meta_parts.insert(0, analysis.theme)
    if analysis.gs_paper_mapping:
        meta_parts.append(analysis.gs_paper_mapping)

    story = [
        Paragraph("UPSC / State PCS Examination Notes", title_style),
        Paragraph(" · ".join(meta_parts), meta_style),
        Paragraph(_safe(analysis.title), heading_style),
    ]

    if analysis.source_hint or analysis.date_hint:
        source_line = " · ".join(p for p in [analysis.date_hint, analysis.source_hint] if p)
        story.append(Paragraph(_safe(source_line), body_style))

    story.append(Paragraph("Exam One-Liner", heading_style))
    story.append(Paragraph(_safe(analysis.exam_one_liner), callout_style))

    if analysis.executive_summary:
        story.append(Paragraph("Executive Summary", heading_style))
        for point in analysis.executive_summary:
            story.append(Paragraph(f"• {_safe(point)}", body_style))

    relevance = (
        f"Prelims: {analysis.prelims_relevance} · "
        f"Mains: {analysis.mains_relevance} · "
        f"Interview: {analysis.interview_relevance} · "
        f"State PCS: {analysis.state_pcs_relevance}"
    )
    story.append(Paragraph(_safe(relevance), meta_style))
    story.append(Spacer(1, 8))

    story.extend(
        _markdown_to_flowables(
            analysis.full_report_markdown,
            heading_style,
            body_style,
            subheading_style,
        )
    )

    story.extend(
        [
            Spacer(1, 12),
            Paragraph("Generated by News Analyst · For study purposes only", meta_style),
        ]
    )

    doc.build(story)
    return output_path
